[manager]
cwd = { fg = "#5ef1ff" }
find_keyword = { bold = true, fg = "#5eff6c" }
find_position = { fg = "#ffffff" }
hovered = { bg = "#7b8496", bold = true, fg = "#ffffff" }
marker_copied = { bg = "#f1ff5e", fg = "#f1ff5e" }
marker_cut = { bg = "#ff6e5e", fg = "#ff6e5e" }
marker_selected = { bg = "#3c4048", fg = "#5eff6c" }
preview_hovered = { bg = "#3c4048", bold = true, fg = "#ffffff" }
tab_active = { bg = "#5ea1ff", fg = "#16181a" }
tab_inactive = { bg = "#3c4048", fg = "#ffffff" }

count_selected = { bg = "#5eff6c", fg = "#16181a" }
count_copied = { bg = "#f1ff5e", fg = "#16181a" }
count_cut = { bg = "#ff6e5e", fg = "#16181a" }

# Border
border_symbol = "│"
border_style = { fg = "#282726" } # ui

[mode]
# Normal mode
normal_main = { fg = "#CECDC3", bg = "#403E3C", bold = true } # tx, ui-3
normal_alt = { fg = "#878580", bg = "#282726" } # tx-2, ui

# Select mode
select_main = { fg = "#100F0F", bg = "#3AA99F", bold = true } # bg, cy
select_alt = { fg = "#3AA99F", bg = "#122F2C" } # cy, cy-900

# Unset mode
unset_main = { fg = "#100F0F", bg = "#3AA99F", bold = true } # bg, cy
unset_alt = { fg = "#3AA99F", bg = "#122F2C" } # cy, cy-900

[status]
overall = { fg = "#CECDC3" } # tx

# Permissions
perm_type = { fg = "#4385BE" } # bl
perm_read = { fg = "#D0A215" } # ye
perm_write = { fg = "#D14D41" } # re
perm_exec = { fg = "#879A39" } # gr
perm_sep = { fg = "#878580" } # tx-2

# Progress
progress_label = { fg = "#100F0F" } # bg
progress_normal = { fg = "#3AA99F", bg = "#1C6C66" } # cy, cy-700
progress_error = { bg = "#D14D41" } # re

[which]
cols = 3
mask = { bg = "#1C1B1A" } # bg-2
cand = { fg = "#D0A215", bold = true } # ye
rest = { fg = "#D0A215", italic = true } # ye
desc = { fg = "#575653" } # tx-3
separator = " "
separator_style = { }

[confirm]
border = { fg = "#403E3C" } # ui-3
title = { fg = "#575653", bold = true } # tx-3
content = { fg = "#CECDC3", bold = true } # tx
list = { fg = "#CECDC3" } # tx
btn_yes = { fg = "#CECDC3", bg = "#403E3C", bold = true } # tx, ui-3
btn_no = { fg = "#878580", bg = "#282726" } # tx-2, ui

[spot]
border = { fg = "#403E3C" } # ui-3
title = { fg = "#575653", bold = true } # tx-3
tbl_col = { fg = "#878580" } # tx-2
tbl_cell = { bg = "#1C1B1A" } # bg-2

[notify]
# Notification title
title_info = { fg = "#4385BE" } # bl
title_warn = { fg = "#DA702C" } # or
title_error = { fg = "#D14D41" } # re

[pick]
border = { fg = "#403E3C", bold = true } # ui-3
active = { fg = "#CECDC3" } # tx
inactive = { fg = "#878580" } # tx-2

[input]
border = { fg = "#403E3C" } # ui-3
title = { fg = "#575653", bold = true } # tx-3
value = { fg = "#CECDC3" } # tx
selected = { bg = "#1C1B1A" } # bg-2

[cmp]
border = { fg = "#403E3C", bold = true } # ui-3
active = { fg = "#878580", bg = "#1C1B1A" } # tx-2, bg-2
inactive = { fg = "#878580" } # tx-2

[tasks]
border = { fg = "#403E3C" } # ui-3
title = { fg = "#575653", bold = true } # tx-3
hovered = { bg = "#1C1B1A" } # bg-2

[help]
on = { fg = "#4385BE" } # bl
run = { fg = "#3AA99F" } # cy
desc = { fg = "#575653", italic = true } # tx-3
hovered = { bg = "#1C1B1A" } # bg-2
footer = { fg = "#CECDC3", bg = "#282726", bold = true } # tx, ui

[filetype]
rules = [
    { fg = "#5ef1ff", mime = "image/*" },
    { fg = "#f1ff5e", mime = "video/*" },
    { fg = "#f1ff5e", mime = "audio/*" },
    { fg = "#bd5eff", mime = "application/zip" },
    { fg = "#bd5eff", mime = "application/gzip" },
    { fg = "#bd5eff", mime = "application/x-tar" },
    { fg = "#bd5eff", mime = "application/x-bzip" },
    { fg = "#bd5eff", mime = "application/x-bzip2" },
    { fg = "#bd5eff", mime = "application/x-7z-compressed" },
    { fg = "#bd5eff", mime = "application/x-rar" },
    { fg = "#bd5eff", mime = "application/xz" },
    { fg = "#5eff6c", mime = "application/doc" },
    { fg = "#5eff6c", mime = "application/pdf" },
    { fg = "#5eff6c", mime = "application/rtf" },
    { fg = "#5eff6c", mime = "application/vnd.*" },
    { bold = true, fg = "#5ea1ff", mime = "inode/directory" },
    { fg = "#ffffff", mime = "*" }
]
